### ISSUE TITLE
Multiple Issues - 0.10.5

### ISSUE THREAD

**Issue by BillyParadise** [ryancp/sailng#13]
Hi,

Great project (I assume :) - I'm assuming Sails has made some breaking changes, and I'm not sure how to resolve them.  

First, 

warn: `sails.config.express` is deprecated; use `sails.config.http` instead.

I couldn't find sails.config.express anywhere, so I'm not sure where to fix it.
Based on https://github.com/balderdashy/sails/issues/1974, it seems like a problem in config/passport.js but again, it's not obvious what needs to be changed.

In addition, once I got past that point, I opened up the browser, and had more problems.

I was getting a blank page, so I took a look in the console, and found the following errors:

Error: [$location:nobase] $location in HTML5 mode requires a <base> tag to be present!
http://errors.angularjs.org/1.3.0/$location/nobase
    at http://localhost:1337/bower_components/angular/angular.js:80:12
    at $LocationProvider.$get (http://localhost:1337/bower_components/angular/angular.js:11060:15)
    at Object.invoke (http://localhost:1337/bower_components/angular/angular.js:4152:17)
    at http://localhost:1337/bower_components/angular/angular.js:3970:37
    at getService (http://localhost:1337/bower_components/angular/angular.js:4111:39)
    at Object.invoke (http://localhost:1337/bower_components/angular/angular.js:4143:13)
    at http://localhost:1337/bower_components/angular/angular.js:3970:37
    at getService (http://localhost:1337/bower_components/angular/angular.js:4111:39)
    at Object.invoke (http://localhost:1337/bower_components/angular/angular.js:4143:13)
    at http://localhost:1337/bower_components/angular/angular.js:3970:37 angular.js:11358

Error: [$compile:ctreq] Controller 'ngInclude', required by directive 'ngInclude', can't be found!
http://errors.angularjs.org/1.3.0/$compile/ctreq?p0=ngInclude&p1=ngInclude
    at http://localhost:1337/bower_components/angular/angular.js:80:12
    at getControllers (http://localhost:1337/bower_components/angular/angular.js:7447:19)
    at nodeLinkFn (http://localhost:1337/bower_components/angular/angular.js:7627:33)
    at compositeLinkFn (http://localhost:1337/bower_components/angular/angular.js:6991:13)
    at compositeLinkFn (http://localhost:1337/bower_components/angular/angular.js:6994:13)
    at nodeLinkFn (http://localhost:1337/bower_components/angular/angular.js:7618:24)
    at compositeLinkFn (http://localhost:1337/bower_components/angular/angular.js:6991:13)
    at publicLinkFn (http://localhost:1337/bower_components/angular/angular.js:6870:30)
    at http://localhost:1337/bower_components/angular/angular.js:1489:27
    at Scope.$eval (http://localhost:1337/bower_components/angular/angular.js:14123:28) angular.js:11358(anonymous function) angular.js:11358

Hoping you are still interested in maintaining this project, and can provide insight.  I'm happy to offer my help in keeping it updated, once I get more fluent in sails.  For now, I'm just a Rails guy trying to get up to speed.

Thx.

**Comment by ryancp** [comment]
This should be fixed by a recent commit.
