### ISSUE TITLE
Unknown authentication strategy "local"

### ISSUE THREAD

**Issue by slinker009** [ryancp/sailng#18]
Hi,my english is a little.
I Install and run the code, I register a new user and send messages, but when I logout and try to login again with the username and password the app show error 500 

Unknown authentication strategy "local" 

error: Sending 500 ("Server Error") response:
 Error: Unknown authentication strategy "local"
    at attempt (c:\nodejs\sailng\node_modules\passport\lib\middleware\authentica
te.js:166:37)
    at authenticate (c:\nodejs\sailng\node_modules\passport\lib\middleware\authe
nticate.js:342:7)
    at Authenticator.passport.callback (c:\nodejs\sailng\api\services\passport.j
s:250:40)
    at Authenticator.bound [as callback] (c:\nodejs\sailng\node_modules\sails\no
de_modules\lodash\dist\lodash.js:729:21)
    at Object.AuthController.callback (c:\nodejs\sailng\api\controllers\AuthCont
roller.js:121:14)
    at bound (c:\nodejs\sailng\node_modules\sails\node_modules\lodash\dist\lodas
h.js:729:21)
    at routeTargetFnWrapper (c:\nodejs\sailng\node_modules\sails\lib\router\bind
.js:179:5)
    at callbacks (c:\nodejs\sailng\node_modules\sails\node_modules\express\lib\r
outer\index.js:164:37)
    at param (c:\nodejs\sailng\node_modules\sails\node_modules\express\lib\route
r\index.js:138:11)
    at pass (c:\nodejs\sailng\node_modules\sails\node_modules\express\lib\router
\index.js:145:5)
    at nextRoute (c:\nodejs\sailng\node_modules\sails\node_modules\express\lib\r
outer\index.js:100:7)
    at callbacks (c:\nodejs\sailng\node_modules\sails\node_modules\express\lib\r
outer\index.js:167:11)
    at c:\nodejs\sailng\node_modules\sails\lib\router\bind.js:187:7
    at c:\nodejs\sailng\api\policies\passport.js:32:7
    at SessionStrategy.strategy.pass (c:\nodejs\sailng\node_modules\passport\lib
\middleware\authenticate.js:318:9)
    at SessionStrategy.authenticate (c:\nodejs\sailng\node_modules\passport\lib\
strategies\session.js:67:10) [Error: Unknown authentication strategy "local"]

I use Windows 8 and Firefox 36.0.4 for this test

**Comment by huguangju** [comment]
I also encountered the same problem.
> mac 10.10.2 (14C109) 
 chrome 42.0.2311.135 (64-bit)

After registering and login operation ,this error is reported.

**Comment by maegnes** [comment]
Also encountered the problem. Does anyone know a solution in the meantime?

**Comment by dermatologist** [comment]
+1

**Comment by ram-you** [comment]
Same problem.

**Comment by oraxpert** [comment]
me too ...

**Comment by PBartrina** [comment]
Having the same issue here:

config/passport.ts
```javascript
import * as passport from 'passport';
import { User } from '../models/user';
import { Strategy as LocalStrategy } from 'passport-local';

const localLogin = new LocalStrategy({ usernameField: 'email' }, function(email, password, done) {

  console.log(email);
  console.log(password);

  User.findOne({ email: email }, function(err, user) {
    if(err) { return done(err); }
    if(!user) { return done(null, false, { message: 'Your login details could not be verified. Please try again.' }); }

    //test instead of user.comparePassword
    user.schema.methods.comparePassword(password, function(err, isMatch) {
      if (err) { return done(err); }
      if (!isMatch) { return done(null, false, { message: "Your login details could not be verified. Please try again." }); }

      return done(null, user);
    });
  });
});

passport.use(localLogin);
```

And then in my router.ts
```javascript
import * as passport from 'passport';

const requireLogin = passport.authenticate('local', { session: false });

...


authRoutes.post('/login', requireLogin, AuthenticationController.login);
```

**Comment by shokry-suleiman** [comment]
mee too

**Comment by AlexandreUser** [comment]
any fix?
